### This is the main config to flash within ESPHome

packages:
  eenernl.senseswitch:
    url: https://github.com/EenerNL/SenseSwitch
    ref: main
    file: senseswitch.yaml
    refresh: 0d
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password