### This is the main config to flash within ESPHome

substitutions:
  name: SenseSwitch-Test
  lower_name: senseswitch-test

packages:
  eenernl.senseswitch: github://EenerNL/SenseSwitch/senseswitch.yaml@main

api:
  encryption:
    key: !secret api_secret_1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password