### This config is made by EenerNL

### GLOBAL SETTINGS ###
substitutions:
  name: "senseswitch"
  friendly_name: "SenseSwitch"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "EenerNL.SenseSwitch"
    version: "2023.8.2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
ota:
captive_portal:

wifi:
  ap:
    ssid: "${friendly_name}"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

# web_server:
#  port: 80
#  include_internal: true

dashboard_import:
  package_import_url: github://eenernl/SenseSwitch/senseswitch.yaml@main
  import_full_config: false

esp32_improv:
  authorizer: none
improv_serial:


### I2C Configuration for I2C-sensors ###
i2c:
  sda: 21
  scl: 22
 
### UART Configuration for HLK-LD2410C ###
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# HLK-LD2410C Configuration
ld2410:
  timeout: 30s
  id: mmwave
  max_move_distance: 6m
  max_still_distance: 2.25m
  g0_move_threshold: 50       # 0m
  g0_still_threshold: 20      #
  g1_move_threshold: 50       # 0m - 0.75m
  g1_still_threshold: 20      #
  g2_move_threshold: 40       # 0.75m - 1.5m
  g2_still_threshold: 40      #
  g3_move_threshold: 30       # 1.5m - 2.25m
  g3_still_threshold: 40      #
  g4_move_threshold: 20       # 2.25m - 3m
  g4_still_threshold: 30      #
  g5_move_threshold: 15       # 3m - 3.75m
  g5_still_threshold: 30      #
  g6_move_threshold: 15       # 3.75m - 4.5m
  g6_still_threshold: 20      #
  g7_move_threshold: 15       # 4.5m - 5.25m
  g7_still_threshold: 20      #
  g8_move_threshold: 15       # 5.25m - 6m
  g8_still_threshold: 20      #
  

### SENSORS ###
sensor:

# BM280 Temperature, Humidity and Pressure
  - platform: bme280
    temperature:
      name: "Temperature"
      id: temperature
      oversampling: 16x
      filters:
        - lambda: 'return x + id(temp_offset).state;'
    pressure:
      name: "Pressure"
      id: pressure
    humidity:
      name: "Humidity"
      id: humidity
      filters:
        - lambda: 'return x + id(hum_offset).state;'
    address: 0x76
    update_interval: 60s
  - platform: template
    name: "Dew Point"
    lambda: |-
      return (243.5*(log(id(humidity).state/100)+((17.67*(id(temperature).state+id(temp_offset).state))/
      (243.5+id(temperature).state+id(temp_offset).state)))/(17.67-log(id(humidity).state/100)-
      ((17.67*(id(temperature).state+id(temp_offset).state))/(243.5+id(temperature).state+id(temp_offset).state))));
    unit_of_measurement: "°C"
    icon: 'mdi:thermometer-alert'

# SGP30 TVOC and eCO2
  - platform: sgp30
    eco2:
      name: "eCO2"
      id: eco2
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      id: tvoc
      accuracy_decimals: 1
    store_baseline: yes
    baseline:
      eco2_baseline: 0x9557
      tvoc_baseline: 0x9C2F
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: temperature
      humidity_source: humidity

# BH1720 Illuminance
  - platform: bh1750
    name: "Illuminance"
    id: illuminance
    address: 0x23
    update_interval: 5s

# HLK-LD2410C Measured values
  - platform: ld2410
    moving_distance:
      name: "mmWave Moving Distance"
    still_distance:
      name: "mmWave Still Distance"
    moving_energy:
      name: "mmWave Move Energy"
    still_energy:
      name: "mmWave Still Energy"
    detection_distance:
      name: "mmWave Detection Distance"  

# Wifi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

 

### TEXT SENSORS
text_sensor:

# Wifi info 
  - platform: wifi_info
    ssid:
      name: WiFi SSID


### BINARY SENSORS ###
binary_sensor:

# Pushbutton for switch relay
  - platform: gpio
    pin:
      number: 19
      mode:
        input: true
        pulldown: true
    name: "Button"
    id: pushbutton
    filters:
      - delayed_on_off: 50ms
    on_press:
      if:
        condition:
          binary_sensor.is_off: relay_mode
        then:
          - switch.toggle: relay
        else:
          - switch.turn_on: relay
          - wait_until:
              binary_sensor.is_off: pushbutton
          - switch.turn_off: relay

# Switch for setting up relay-functionality
  - platform: gpio
    pin:
      number: 18
      mode:
        input: true
        pulldown: true
    name: "Relay Pulsemode"
    id: relay_mode

# HLK-LD2410 Occupancy sensors
  - platform: ld2410
    has_target:
      name: "mmWave Presence"
    has_moving_target:
      name: "mmWave Moving Target"
    has_still_target:
      name: "mmWave Still Target"


### SWITCHES ###
switch:

# Relay output
  - platform: gpio
    pin:
      number: 23
      mode:
        output: true
    name: "Relay"
    id: relay
    on_turn_on:
      output.turn_on: relay_status_led
    on_turn_off:
      output.turn_off: relay_status_led


### OUTPUTS ###
output:

# StatusLED for indicating relay-status
  - id: relay_status_led
    platform: gpio
    pin: 2


### NUMBERS ###
number:

# Setting for minimum lux-value
  - platform: template
    name: "Minimum Lux"
    id: min_lux
    entity_category: CONFIG
    mode: box
    unit_of_measurement: lx
    initial_value: 100
    min_value: 0
    max_value: 500
    step: 1
    optimistic: true

# Setting temperature offset for calibrating temperature readings
  - platform: template
    name: "Temperature offset"
    id: temp_offset
    unit_of_measurement: "°C"
    min_value: -20
    max_value: 20
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:thermometer"
    entity_category: CONFIG

# Setting humidity offset for calibrating humidity readings
  - platform: template
    name: "Humidity offset"
    id: hum_offset
    unit_of_measurement: "%"
    min_value: -20
    max_value: 20
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:water-percent"
    entity_category: CONFIG
