esphome:
  name: "${name}"
  friendly_name: "${name}"
  project:
    name: "SenseSwitch by EenerNL"
    version: "23.07.01"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

ota:

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  ap:
    ssid: "${name}"

captive_portal:

web_server:
  port: 80
  include_internal: true
 

### I2C Bus for Sensors ###
i2c:
  sda: 21
  scl: 22
 

### LD2410C configuration
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 25600
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 30s
  id: mmwave
  max_move_distance: 6m
  max_still_distance: 2.25m
  g0_move_threshold: 50       # 0m
  g0_still_threshold: 20      #
  g1_move_threshold: 50       # 0m - 0.75m
  g1_still_threshold: 20      #
  g2_move_threshold: 40       # 0.75m - 1.5m
  g2_still_threshold: 40      #
  g3_move_threshold: 30       # 1.5m - 2.25m
  g3_still_threshold: 40      #
  g4_move_threshold: 20       # 2.25m - 3m
  g4_still_threshold: 30      #
  g5_move_threshold: 15       # 3m - 3.75m
  g5_still_threshold: 30      #
  g6_move_threshold: 15       # 3.75m - 4.5m
  g6_still_threshold: 20      #
  g7_move_threshold: 15       # 4.5m - 5.25m
  g7_still_threshold: 20      #
  g8_move_threshold: 15       # 5.25m - 6m
  g8_still_threshold: 20      #
  

### Sensors ###
sensor:
  - platform: bme280
    temperature:
      name: "${name} Temperature"
      id: temperature
      oversampling: 16x
    pressure:
      name: "${name} Pressure"
      id: pressure
    humidity:
      name: "${name} Humidity"
      id: humidity
    address: 0x76
    update_interval: 60s

  - platform: sgp30
    eco2:
      name: "${name} eCO2"
      id: eco2
      accuracy_decimals: 1
    tvoc:
      name: "${name} TVOC"
      id: tvoc
      accuracy_decimals: 1
    store_baseline: yes
    baseline:
      eco2_baseline: 0x955D
      tvoc_baseline: 0x9C30
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: temperature
      humidity_source: humidity

  - platform: bh1750
    name: "${name} Illuminance"
    address: 0x23
    update_interval: 5s

  - platform: ld2410
    moving_distance:
      name: "${name} mmWave Moving Distance"
    still_distance:
      name: "${name} mmWave Still Distance"
    moving_energy:
      name: "${name} mmWave Moving Energy"
    still_energy:
      name: "${name} mmWave Still Energy"
    detection_distance:
      name: "${name} mmWave Detection Distance"  


### CONTROLLING RELAY ###
binary_sensor:
  - platform: gpio
    pin:
      number: 19
      mode:
        input: true
        pulldown: true
    name: "${name} Button"
    id: pushbutton
    filters:
      - delayed_on_off: 50ms
    on_press:
      if:
        condition:
          binary_sensor.is_off: relay_mode
        then:
          - switch.toggle: relay
        else:
          - switch.turn_on: relay
          - wait_until:
              binary_sensor.is_off: pushbutton
          - switch.turn_off: relay
  - platform: gpio
    pin:
      number: 18
      mode:
        input: true
        pulldown: true
    name: "${name} Relay Mode"
    id: relay_mode
    internal: true

  - platform: ld2410
    has_target:
      name: "${name} mmWave Presence"
    has_moving_target:
      name: "${name} mmWave Moving Target"
    has_still_target:
      name: "${name} mmWave Still Target"

switch:
  - platform: gpio
    pin: 23
    name: "${name} Relay"
    id: relay
    on_turn_on:
      output.turn_on: relay_status_led
    on_turn_off:
      output.turn_off: relay_status_led

output:
  - id: relay_status_led
    platform: gpio
    pin: 2


### CONFIG ENTITIES ###
number:
  - platform: template
    name: "${name} Minimum Lux"
    id: min_lux
    entity_category: CONFIG
    mode: box
    unit_of_measurement: lx
    initial_value: 100
    min_value: 0
    max_value: 500
    step: 1
    optimistic: true
   