esphome:
  name: "senseswitch-2023-01"
  friendly_name: SenseSwitch-2023-01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CSgnvIFsZucpUY2VfRiWlFMiLogzxuYi0zpaI5H5bWg="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SenseSwitch-2023-01"
    password: "hrofbMFcdjwy"

captive_portal:

web_server:
  port: 80
  include_internal: true

### I2C Bus for Sensors ###
i2c:
  sda: 21
  scl: 22

### Sensors ###
sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      id: temperature
      oversampling: 16x
    pressure:
      name: "Pressure"
      id: pressure
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x76
    update_interval: 60s

  - platform: sgp30
    eco2:
      name: "eCO2"
      id: eco2
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      id: tvoc
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: temperature
      humidity_source: humidity

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 1s

### LD2410C ###

### CONTROLLING RELAY ###
binary_sensor:
  - platform: gpio
    pin: 26
    name: "Button"
    id: pushbutton
    filters:
      - delayed_on_off: 100ms
    on_press:
      if:
        condition:
          binary_sensor.is_off: relay_mode
        then:
          - switch.toggle: relay
        else:
          - switch.turn_on: relay
          - wait_until:
              binary_sensor.is_off: pushbutton
          - switch.turn_off: relay
  - platform: gpio
    pin: 18
    name: "Relay Mode"
    id: relay_mode
    internal: true

switch:
  - platform: gpio
    pin: 16
    name: "Relay"
    id: relay
    on_turn_on:
      output.turn_on: relay_status_led
    on_turn_off:
      output.turn_off: relay_status_led

output:
  - id: relay_status_led
    platform: gpio
    pin: 2